carText = "Garantizamos la seguridad de tu auto. Facilitamos tu d&iacute;a a d&iacute;a para que t&uacute; y tu familia viajen tranquilos."
travelText = "Gan&aacute; tranquilidad viajando. Contamos con cobertura internacional para respaldarte en todo."
homeText = "Cuidamos tu hogar para que ganes tranquilidad. Garantizamos tu patrimonio con coberturas a medida."
rentText = "Aseguramos confianza entre inquilino y propietario para el cumplimiento del pago del alquiler."
healthText = "Te proponemos distinas opciones para que t&uacute; y tus seres queridos se sientan m&aacute;s protegidos."
maritimeText = "Cubrimos tu embarcaci&oacute;n mientras est&eacute; a flote, en tierra o en su transporte por este medio."
businessText = "Acompa&ntilde;amos tu negocio desde cerca, soluciones para proteger el patrimonio del empresario."
transportText = "Brindamos la tranquilidad necesaria sobre posibles da&ntilde;os o p&eacute;rdidas de bienes durante su transporte."
agroText = "Ofrecemos una amplia gama de coberturas para sentrise seguro con su producci&oacute;n agr&iacute;cola."
motobikeText = "Garantizamos la seguridad de tu moto con coberturas que te brinden la m&aacute;xima tranquilidad y protecci&oacute;n."
bikeText = "Brindamos tranquilidad en caso de hurto y da&ntilde;os a terceros, para que puedas entrenar y disfrutar seguro."
jetBoatText = "Ofrecemos un seguro completo para que puedas navegar sin preocupaci&oacute;n con tu moto de agua."
workHurtText = "Queremos protegerte en todo momento ante eventos inesperados y as&iacute;  estar siempre prevenido."
cristalsText = "Brindamos seguro de rotura de cristales y protegemos tu econom&iacute;a frente a los riesgos m&aacute;s habituales."
uberText = "Estamos preparados para protegerte a t&iacute; y a todas las personas que utilizan la plataforma."

document.getElementById("carText").innerHTML = carText;
document.getElementById("travelText").innerHTML = travelText;
document.getElementById("homeText").innerHTML = homeText;
document.getElementById("rentText").innerHTML = rentText;
document.getElementById("healthText").innerHTML = healthText;
document.getElementById("maritimeText").innerHTML = maritimeText;
document.getElementById("businessText").innerHTML = businessText;
document.getElementById("transportText").innerHTML = transportText;
document.getElementById("agroText").innerHTML = agroText;
document.getElementById("motobikeText").innerHTML = motobikeText;
document.getElementById("bikeText").innerHTML = bikeText;
document.getElementById("jetBoatText").innerHTML = jetBoatText;
document.getElementById("workHurtText").innerHTML = workHurtText;
document.getElementById("cristalsText").innerHTML = cristalsText;
document.getElementById("uberText").innerHTML = uberText;
