carText = "Garantizamos la seguridad de tu auto. Facilitamos tu día a día para que tú y tu familia viajen tranquilos."
travelText = "Ganá tranquilidad viajando. Contamos con cobertura internacional para respaldarte en todo."
homeText = "Cuidamos tu hogar para que ganes tranquilidad. Garantizamos tu patrimonio con coberturas a medida."
rentText = "Aseguramos confianza entre inquilino y propietario para el cumplimiento del pago del alquiler."
healthText = "Te proponemos distinas opciones para que tú y tus seres queridos se sientan más protegidos."
maritimeText = "Cubrimos tu embarcación mientras esté a flote, en tierra o en su transporte por este medio."
businessText = "Acompañamos tu negocio desde cerca, soluciones para proteger el patrimonio del empresario."
transportText = "Brindamos la tranquilidad necesaria sobre posibles daños o pérdidas de bienes durante su transporte."
agroText = "Ofrecemos una amplia gama de coberturas para sentrise seguro con su producción agrícola."
motobikeText = "Garantizamos la seguridad de tu moto con coberturas que te brinden la máxima tranquilidad y protección."
bikeText = "Brindamos tranquilidad en caso de hurto y daños a terceros, para que puedas entrenar y disfrutar seguro."
jetBoatText = "Ofrecemos un seguro completo para que puedas navegar sin preocupación con tu moto de agua."
workHurtText = "Queremos protegerte en todo momento ante eventos inesperados y así  estar siempre prevenido."
cristalsText = "Brindamos seguro de rotura de cristales y protegemos tu economía frente a los riesgos más habituales."
uberText = "Estamos preparados para protegerte a tí y a todas las personas que utilizan la plataforma."

document.getElementById("carText").innerHTML = carText;
document.getElementById("travelText").innerHTML = travelText;
document.getElementById("homeText").innerHTML = homeText;
document.getElementById("rentText").innerHTML = rentText;
document.getElementById("healthText").innerHTML = healthText;
document.getElementById("maritimeText").innerHTML = maritimeText;
document.getElementById("businessText").innerHTML = businessText;
document.getElementById("transportText").innerHTML = transportText;
document.getElementById("agroText").innerHTML = agroText;
document.getElementById("motobikeText").innerHTML = motobikeText;
document.getElementById("bikeText").innerHTML = bikeText;
document.getElementById("jetBoatText").innerHTML = jetBoatText;
document.getElementById("workHurtText").innerHTML = workHurtText;
document.getElementById("cristalsText").innerHTML = cristalsText;
document.getElementById("uberText").innerHTML = uberText;
